server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/db_oficina
        username: postgres
        password: wasd
    jpa:
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.PostgreSQLDialect
            jdbc:
                lob.non-contextual-creation: true
        properties:
            hibernate:
                show_sql: true
